AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Rails:
  Enabled: true

Style/Alias:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BlockEndNewline:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/PredicateName:
  Enabled: false # Doesn't understand `has_secure_token`, though there's promising discussion here: https://github.com/bbatsov/rubocop/issues/1741

Style/Next:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false

Metrics/ParameterLists:
  Max: 6

Style/DotPosition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false # At the moment MultiEditble is the problem, for has_many through we'd need to interpolate the join table for Configs and Docs

# Disable some New Rules from Rubocop 0.39
Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Description: >-
                 Checks for ambiguous regexp literals in the first argument of
                 a method invocation without parenthesis.
  Enabled: false
